name: Structra
version: '${project.version}'
main: com.desoi.structra.Structra
api-version: '1.17'
authors: [ desaxx, aysihuniks ]
commands:
  structra:
    description: Main command of the plugin.
permissions:
  structra.admin:
    default: op
    children:
      structra.paste.*: true
      structra.write: true
      structra.select: true
      structra.tool: true
      structra.delete.*: true
  structra.paste.*:
    default: op
  structra.write:
    default: op
  structra.select:
    default: op
  structra.tool:
    default: op
  structra.delete.*:
    default: op